version: '3.3'

services:

  cerebro:
    image: yannart/cerebro
    ports:
      - 9001:9000
    volumes:
      - ./config/application.conf:/opt/cerebro/conf/application.conf:ro
    depends_on:
      - elasticsearch
