version: '2'

services:

  cerebro:
    image: yannart/cerebro
    ports:
      # Because 9000 is already used by portainer
      - 9000:9001
    volumes:
      - ./extensions/cerebro/config/application.conf:/opt/cerebro/conf/application.conf:ro
    depends_on:
      - elasticsearch
