---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana-full.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

## x-pack
#
# apm
#xpack.apm.enabled:     false
xpack.apm.ui.enabled : false
#
# Machine learning

# Enabling the following line causes kibana to optimze the cache at startup which takes seveall minutes
xpack.ml.enabled: false
