---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

##########################################
## End of original file from docker-elk ##
##########################################

path.config: /usr/share/logstash/pipeline

# With the next line reloading works. It is not necessary to add something like "environment: LS_OPTS: -r" to the compose file.
config.reload.automatic: true
config.reload.interval:  1s
