---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
#xpack.monitoring.elasticsearch.url: http://elasticsearch:9200

## X-Pack security credentials
#
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: changeme  # unset by default. see:
                                                   # https://www.elastic.co/guide/en/logstash/current/ls-security.html#ls-monitoring-user

##########################################
## End of original file from docker-elk ##
##########################################

path.config: /usr/share/logstash/pipeline

# With the next line reloading works. It is not necessary to add something like "environment: LS_OPTS: -r" to the compose file.
config.reload.automatic: true
config.reload.interval:  1s
