---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-oss.yml
#
http.host: "0.0.0.0"

# The following isn't needed because we have the pipelines.yml
#path.config: /usr/share/logstash/pipeline

##########################################
## End of original file from docker-elk ##
##########################################

# With the next line reloading works. It is not necessary to add something like "environment: LS_OPTS: -r" to the compose file.
config.reload.automatic: true
config.reload.interval:  1s

## x-pack
#
# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.url: "elasticsearch:9200"